site_name: Cyber and Law | Personal Incident Response Framework
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
  font:
    text: "Work Sans"
    code: "Fira Code"
nav:
  - About: index.md
  - PIRF Profiles: pirf-profiles.md
  - Incidents:
      - Prevent: framework/prevention/prevention.md
      - Detect: framework/detection/detection.md
      - Remediate: framework/remediation/remediation.md
extra_css:
  - overrides/extra.css
extra:
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
