site_name: Cyber and Law | Personal Incident Response Framework
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: black
      accent: black
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: "Georgia"
    code: "Fira Code"
nav:
  - Home: index.md
  - Framework:
      - Overview: framework/index.md
      - Detect: framework/prevention/prevention/prevention.md
      - Respond: framework/detection/detection/detection.md
      - Recover: framework/remediation/remediation/remediation.md
extra_css:
  - overrides/extra.css
extra:
  favicon: images/favicon.png
  logo: images/logo.png
